In [1]:
# pandas is a fast, powerful, flexible and easy yo use open source data analysis and manipulartion tool built on top of the pyhton programming language
# pandas was developed in 2008 by Mckinney
# very useful with structured data (eg. tabular data)

In [1]:
import pandas as pd
dataframe_path = "../00.1-data/services.csv"

In [2]:
# reading a cvs (comma separated values) file using pandas
df = pd.read_csv(dataframe_path)
# by default pandas understands the 1st row are column names
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [18]:
# in case if the data has no header (column name)
pd.read_csv(dataframe_path, header = None)
# internal integer indexes are provided by pandas for both rows and columns

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [19]:
# suppose we don't want the first rows
pd.read_csv(dataframe_path, skiprows=2)

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [20]:
# lets say we want to see only 3 columns
pd.read_csv(dataframe_path, usecols=["program_id", "application_process"])

    program_id                                application_process
0          NaN                         Walk in or apply by phone.
1          NaN                 Apply by phone for an appointment.
2          NaN        Phone for information (403-4300 Ext. 4322).
3          NaN                                    Apply by phone.
4          NaN                             Phone for information.
5          NaN  Walk in or apply by phone for membership appli...
6          NaN  Apply by phone or be referred by a doctor, soc...
7          NaN                                    Apply by phone.
8          NaN  Walk in. Proof of residency in California requ...
9          NaN  Walk in. Proof of California residency to rece...
10         NaN  Walk in. Proof of California residency require...
11         NaN  Walk in or apply by phone, email or webpage re...
12         NaN  Walk in. Proof of California residency require...
13         NaN  Call for appointment. Referral from human serv...
14         NaN          Walk in or through other agency referral.
15         NaN  Walk in. Written application, identification r...
16         NaN                              Call for information.
17         NaN  Call for screening appointment. Medical visits...
18         NaN     Call for screening appointment (650-347-3648).
19         NaN                                           Walk in.
20         NaN                    By phone during business hours.
21         NaN                  Walk in or apply by phone or mail
22         NaN                  Walk in or apply by phone or mail

In [21]:
print(pd.read_csv(dataframe_path))

    id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN
1    2            2         NaN                       NaN
2    3            3         NaN                       NaN
3    4            4         NaN                       NaN
4    5            5         NaN                       NaN
5    6            6         NaN                       NaN
6    7            7         NaN                       NaN
7    8            8         NaN                       NaN
8    9            9         NaN                       NaN
9   10           10         NaN                       NaN
10  11           11         NaN                       NaN
11  12           12         NaN                       NaN
12  13           13         NaN                       NaN
13  14           14         NaN                       NaN
14  15           15         NaN                       NaN
15  16           16         NaN                       NaN
16  17           17         NaN                       NaN
17  18           18         NaN                       NaN
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.
1                     NaN                 Apply by phone for an appointment.
2                     NaN        Phone for information (403-4300 Ext. 4322).
3                     NaN                                    Apply by phone.
4                     NaN                             Phone for information.
5                     NaN  Walk in or apply by phone for membership appli...
6                     NaN  Apply by phone or be referred by a doctor, soc...
7                     NaN                                    Apply by phone.
8                     NaN  Walk in. Proof of residency in California requ...
9                     NaN  Walk in. Proof of California residency to rece...
10                    NaN  Walk in. Proof of California residency require...
11                    NaN  Walk in or apply by phone, email or webpage re...
12                    NaN  Walk in. Proof of California residency require...
13                    NaN  Call for appointment. Referral from human serv...
14                    NaN          Walk in or through other agency referral.
15                    NaN  Walk in. Written application, identification r...
16                    NaN                              Call for information.
17                    NaN  Call for screening appointment. Medical visits...
18                    NaN     Call for screening appointment (650-347-3648).
19                    NaN                                           Walk in.
20                    NaN                    By phone during business hours.
21  Fotos para pasaportes                  Walk in or apply by phone or mail
22                    NaN                  Walk in or apply by phone or mail

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...
1        Residents of San Mateo County age 55 or over
2   Older adults age 55 or over who can benefit fr...
3   Parents, children, families with problems of c...
4   Low-income working families with children tran...
5                                             Any age
6   Older adults who have memory or sensory loss, ...
7   Senior citizens age 60 or over, disabled indiv...
8      Ethnic minorities, especially Spanish speaking
9                                                 NaN
10                                                NaN
11  Adults, parents, children in 1st-12th grades i...
12                                                NaN
13  Individuals or families with low or no income ...
14  Adult alcoholic/drug addictive men and women w...
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
0   A walk-in center for older adults that provide...
1   Provides training and job placement to eligibl...
2   Offers supportive counseling services to San M...
3   Provides supervised visitation services and a ...
4   Provides fixed 8% short term loans to eligible...
5   A multipurpose center offering a wide variety ...
6   Rosener House is a day center for older adults...
7   Delivers a hot meal to the home of persons age...
8   Provides general reading material, including b...
9   Provides general reading and media materials, ...
10  Provides general reading materials, including ...
11  Offers an intergenerational literacy program f...
12  Provides general reading materials, including ...
13  Provides food, clothing, bus tokens and shelte...
14  Provides a long-term (6-12 month) residential ...
15  Provides emergency assistance including food a...
16  Provides emergency food, clothing and furnitur...
17  By appointment only, Project Smile provides a ...
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                          eligibility                  email  \
0   Age 55 or over for most programs, age 60 or ov...                    NaN
1   Age 55 or over, county resident and willing an...                    NaN
2         Resident of San Mateo County age 55 or over                    NaN
3                                                 NaN                    NaN
4   Eligibility: Low-income family with legal cust...                    NaN
5                                                 NaN                    NaN
6                                      Age 18 or over                    NaN
7             Homebound person unable to cook or shop                    NaN
8     Resident of California to obtain a library card                    NaN
9             Resident of California to obtain a card                    NaN
10  Resident of California to obtain a library car...                    NaN
11  English-speaking adult reading at or below 7th...                    NaN
12    Resident of California to obtain a library card                    NaN
13  None for most services. For emergency assistan...                    NaN
14  Age 21-60, detoxed, physically able and willin...                    NaN
15                      None for emergency assistance                    NaN
16                                Low-income families                    NaN
17    Low-income person without access to health care                    NaN
18    Low-income person without access to health care                    NaN
19                                                NaN                    NaN
20                                                NaN                    NaN
21                                                NaN  passports@example.org
22                                                NaN                    NaN

    ...                            interpretation_services  \
0   ...                                                NaN
1   ...                                                NaN
2   ...                                                NaN
3   ...                                                NaN
4   ...                                                NaN
5   ...                                                NaN
6   ...                                                NaN
7   ...                                                NaN
8   ...                                                NaN
9   ...                                                NaN
10  ...                                                NaN
11  ...                                                NaN
12  ...                                                NaN
13  ...                                                NaN
14  ...                                                NaN
15  ...                                                NaN
16  ...                                                NaN
17  ...                                                NaN
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN
2   Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN
4      COMMUNITY SERVICES, Speakers, Automobile Loans       NaN
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
8   EDUCATION SERVICES, Library, Libraries, Public...       NaN
9   EDUCATION SERVICES, Library, Libraries, Public...       NaN
10  EDUCATION SERVICES, Library, Libraries, Public...       NaN
11  EDUCATION SERVICES, Adult, Alternative, Litera...       NaN
12  EDUCATION SERVICES, Library, Libraries, Public...       NaN
13  COMMUNITY SERVICES, Interpretation/Translation...       NaN
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...       NaN
15  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
16  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
17  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                                    name  \
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

                          required_documents  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  Government-issued picture identification
22                                       NaN

                            service_areas    status  \
0                                   Colma    active
1                        San Mateo County    active
2                        San Mateo County    active
3                        San Mateo County    active
4                        San Mateo County    active
5                        San Mateo County    active
6     Belmont, Burlingame, East Palo Alto    active
7                 Belmont, East Palo Alto    active
8                        San Mateo County    active
9                        San Mateo County    active
10                       San Mateo County    active
11                              Daly City    active
12                       San Mateo County    active
13    Belmont, Burlingame, East Palo Alto    active
14       Alameda County, San Mateo County    active
15                                    NaN    active
16  Colma, Daly City, South San Francisco    active
17                         East Palo Alto    active
18                    Belmont, Burlingame    active
19                                    NaN   defunct
20                       San Mateo County  inactive
21       Alameda County, San Mateo County    active
22       San Mateo County, Alameda County    active

                                            wait_time                 website  \
0                                            No wait.                     NaN
1                                             Varies.                     NaN
2                                             Varies.                     NaN
3                                            No wait.                     NaN
4                                                 NaN                     NaN
5                                            No wait.                     NaN
6                                            No wait.                     NaN
7                                            No wait.                     NaN
8                                            No wait.                     NaN
9                                            No wait.                     NaN
10                                           No wait.                     NaN
11  Depends on availability of tutors for small gr...                     NaN
12                                           No wait.                     NaN
13                                  Up to 20 minutes.                     NaN
14  Varies according to available beds for men and...                     NaN
15                                           No wait.                     NaN
16                                                NaN                     NaN
17                                            Varies.                     NaN
18                                            Varies.                     NaN
19                                                NaN                     NaN
20                                                NaN                     NaN
21                                No wait to 2 weeks.  http://www.example.com
22                                 No wait to 2 weeks  http://www.example.com

                                taxonomy_ids
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  105, 108, 108-05, 108-05-01, 111, 111-05
22                                       NaN

[23 rows x 22 columns]

In [22]:
# data structures in pandas >> here data are stored in the form of series and dataframe
# series >> 1 dimentional in nature
# dataframe >> 2 dimentional in nature

In [25]:
# what type is the variable 'df' we were using till now
type(df)

pandas.DataFrame

In [27]:
# access a particular column
df.application_process

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [61]:
# another way to do the same
df["application_process"] # prefered method

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [31]:
# a column of a dataframe is a series
type(df["application_process"])

pandas.Series

In [3]:
lvar = [1, 2, 3, 4]
s = pd.Series(lvar)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
# we can use slicing techniqe in series just like in a list
print(s[1:])
print(s[2:4])

1    2
2    3
3    4
dtype: int64
2    3
3    4
dtype: int64

In [8]:
# by default the indexes are integer
# but we can have custom indexes
d = pd.Series([100, 200, 300], index = ["jkmloom", "jkmcode", "jkmjatin"])
print(d)

jkmloom     100
jkmcode     200
jkmjatin    300
dtype: int64

In [9]:
type(d)

pandas.Series

In [11]:
# slicing on custom index
d["jkmcode"]

np.int64(200)

In [12]:
# to see all the index of the series
d.index

Index(['jkmloom', 'jkmcode', 'jkmjatin'], dtype='str')

In [13]:
# to reset index
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [15]:
# convert a series into dataframe
pd.DataFrame(d)

            0
jkmloom   100
jkmcode   200
jkmjatin  300

In [20]:
# multiple series combines to form a dataframe 
df_2 = pd.DataFrame(d)
print(f"Dataframe:\n{df_2}\n{"***"*14}\nVariable type: {type(df_2)}")

Dataframe:
            0
jkmloom   100
jkmcode   200
jkmjatin  300
******************************************
Variable type: <class 'pandas.DataFrame'>

In [22]:
# first 5 rows of the datafram
print(df.head())

   id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN
1   2            2         NaN               NaN            NaN
2   3            3         NaN               NaN            NaN
3   4            4         NaN               NaN            NaN
4   5            5         NaN               NaN            NaN

                           application_process  \
0                   Walk in or apply by phone.
1           Apply by phone for an appointment.
2  Phone for information (403-4300 Ext. 4322).
3                              Apply by phone.
4                       Phone for information.

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...
1       Residents of San Mateo County age 55 or over
2  Older adults age 55 or over who can benefit fr...
3  Parents, children, families with problems of c...
4  Low-income working families with children tran...

                                         description  \
0  A walk-in center for older adults that provide...
1  Provides training and job placement to eligibl...
2  Offers supportive counseling services to San M...
3  Provides supervised visitation services and a ...
4  Provides fixed 8% short term loans to eligible...

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...
1  Age 55 or over, county resident and willing an...   NaN  ...
2        Resident of San Mateo County age 55 or over   NaN  ...
3                                                NaN   NaN  ...
4  Eligibility: Low-income family with legal cust...   NaN  ...

  interpretation_services                                           keywords  \
0                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...
1                     NaN  EMPLOYMENT/TRAINING SERVICES, Job Development,...
2                     NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...
3                     NaN  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...
4                     NaN     COMMUNITY SERVICES, Speakers, Automobile Loans

  languages                               name required_documents  \
0       NaN    Fair Oaks Adult Activity Center                NaN
1       NaN   Second Career Employment Program                NaN
2       NaN             Senior Peer Counseling                NaN
3       NaN           Family Visitation Center                NaN
4       NaN  Economic Self-Sufficiency Program                NaN

      service_areas  status wait_time website taxonomy_ids
0             Colma  active  No wait.     NaN          NaN
1  San Mateo County  active   Varies.     NaN          NaN
2  San Mateo County  active   Varies.     NaN          NaN
3  San Mateo County  active  No wait.     NaN          NaN
4  San Mateo County  active       NaN     NaN          NaN

[5 rows x 22 columns]

In [24]:
# last five rows of the dataframe
print(df.tail())

    id  location_id  program_id         accepted_payments  \
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                             application_process  \
18                    NaN  Call for screening appointment (650-347-3648).
19                    NaN                                        Walk in.
20                    NaN                 By phone during business hours.
21  Fotos para pasaportes               Walk in or apply by phone or mail
22                    NaN               Walk in or apply by phone or mail

                                             audience  \
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                        eligibility                  email  \
18  Low-income person without access to health care                    NaN
19                                              NaN                    NaN
20                                              NaN                    NaN
21                                              NaN  passports@example.org
22                                              NaN                    NaN

    ...                            interpretation_services  \
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                               name                        required_documents  \
18    San Mateo Free Medical Clinic                                       NaN
19        Service with blank fields                                       NaN
20  Service for Admin Test Location                                       NaN
21                  Passport Photos  Government-issued picture identification
22             Example Service Name                                       NaN

                       service_areas    status            wait_time  \
18               Belmont, Burlingame    active              Varies.
19                               NaN   defunct                  NaN
20                  San Mateo County  inactive                  NaN
21  Alameda County, San Mateo County    active  No wait to 2 weeks.
22  San Mateo County, Alameda County    active   No wait to 2 weeks

                   website                              taxonomy_ids
18                     NaN                                       NaN
19                     NaN                                       NaN
20                     NaN                                       NaN
21  http://www.example.com  105, 108, 108-05, 108-05-01, 111, 111-05
22  http://www.example.com                                       NaN

[5 rows x 22 columns]

In [25]:
# defined number of rows from the end
print(df.tail(3)) # defined number here: 3

    id  location_id  program_id         accepted_payments  \
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                application_process  \
20                    NaN    By phone during business hours.
21  Fotos para pasaportes  Walk in or apply by phone or mail
22                    NaN  Walk in or apply by phone or mail

                                             audience  \
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description eligibility  \
20                                just a test service         NaN
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...         NaN
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...         NaN

                    email  ...  \
20                    NaN  ...
21  passports@example.org  ...
22                    NaN  ...

                              interpretation_services  \
20                                                NaN
21  We offer 3-way interpretation services over th...
22                                                NaN

                                      keywords languages  \
20                                         NaN       NaN
21                             Salud, Medicina   Spanish
22  Ruby on Rails/Postgres/Redis, testing, wic       NaN

                               name                        required_documents  \
20  Service for Admin Test Location                                       NaN
21                  Passport Photos  Government-issued picture identification
22             Example Service Name                                       NaN

                       service_areas    status            wait_time  \
20                  San Mateo County  inactive                  NaN
21  Alameda County, San Mateo County    active  No wait to 2 weeks.
22  San Mateo County, Alameda County    active   No wait to 2 weeks

                   website                              taxonomy_ids
20                     NaN                                       NaN
21  http://www.example.com  105, 108, 108-05, 108-05-01, 111, 111-05
22  http://www.example.com                                       NaN

[3 rows x 22 columns]

In [26]:
# shape (number of columns and rows) of the dataframe
print(f"Dataframe shape: {df.shape}")

Dataframe shape: (23, 22)

In [27]:
# columns of a dataframe
print(df.columns)

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [28]:
# convert the columns into a list
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [29]:
# see a randow row from the dataframe
df.sample() # default: returns 1 value

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"

In [34]:
# defined number of random rows from a dataframe
print(df.sample(3))

    id  location_id  program_id         accepted_payments  \
21  22           22         NaN  Cash, Check, Credit Card
5    6            6         NaN                       NaN
22  23           22         NaN                       NaN

           alternate_name                                application_process  \
21  Fotos para pasaportes                  Walk in or apply by phone or mail
5                     NaN  Walk in or apply by phone for membership appli...
22                    NaN                  Walk in or apply by phone or mail

                                             audience  \
21  Profit and nonprofit businesses, the public, m...
5                                             Any age
22  Second service and nonprofit businesses, the p...

                                          description eligibility  \
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...         NaN
5   A multipurpose center offering a wide variety ...         NaN
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...         NaN

                    email  ...  \
21  passports@example.org  ...
5                     NaN  ...
22                    NaN  ...

                              interpretation_services  \
21  We offer 3-way interpretation services over th...
5                                                 NaN
22                                                NaN

                                             keywords languages  \
21                                    Salud, Medicina   Spanish
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                                    name  \
21                       Passport Photos
5   Little House Recreational Activities
22                  Example Service Name

                          required_documents  \
21  Government-issued picture identification
5                                        NaN
22                                       NaN

                       service_areas  status            wait_time  \
21  Alameda County, San Mateo County  active  No wait to 2 weeks.
5                   San Mateo County  active             No wait.
22  San Mateo County, Alameda County  active   No wait to 2 weeks

                   website                              taxonomy_ids
21  http://www.example.com  105, 108, 108-05, 108-05-01, 111, 111-05
5                      NaN                                       NaN
22  http://www.example.com                                       NaN

[3 rows x 22 columns]

In [38]:
# check infromation about the dataframe in pandas
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      str
 4   alternate_name           1 non-null      str
 5   application_process      23 non-null     str
 6   audience                 14 non-null     str
 7   description              23 non-null     str
 8   eligibility              17 non-null     str
 9   email                    1 non-null      str
 10  fees                     21 non-null     str
 11  funding_sources          21 non-null     str
 12  interpretation_services  1 non-null      str
 13  keywords                 21 non-null     str
 14  languages                1 non-null      str
 15  name                     23 non-null     str
 16  required_documents       1 non-null      str
 17  service_areas            21 non-null     str
 18  status                   23 non-null     str
 19  wait_time                19 non-null     str
 20  website                  2 non-null      str
 21  taxonomy_ids             1 non-null      str
dtypes: float64(1), int64(2), str(19)
memory usage: 4.1 KB

In [40]:
# check data types in a dataframe
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [43]:
# revise: dataframe is a collection of series
print(type(df['id']))

<class 'pandas.Series'>

In [44]:
type(df["application_process"])

pandas.Series

In [45]:
list(df["application_process"])

['Walk in or apply by phone.',
 'Apply by phone for an appointment.',
 'Phone for information (403-4300 Ext. 4322).',
 'Apply by phone.',
 'Phone for information.',
 'Walk in or apply by phone for membership application.',
 'Apply by phone or be referred by a doctor, social worker or other professional. All prospective participants are interviewed individually before starting the program. A recent physical examination is required, including a TB test.',
 'Apply by phone.',
 'Walk in. Proof of residency in California required to receive a library card.',
 'Walk in. Proof of California residency to receive a library card.',
 'Walk in. Proof of California residency required to receive a library card.',
 'Walk in or apply by phone, email or webpage registration.',
 'Walk in. Proof of California residency required to receive a library card.',
 'Call for appointment. Referral from human service professional preferred for emergency assistance.',
 'Walk in or through other agency referral.',
 'Walk in. Written application, identification required for emergency assistance.',
 'Call for information.',
 'Call for screening appointment. Medical visits are by appointment only.',
 'Call for screening appointment (650-347-3648).',
 'Walk in.',
 'By phone during business hours.',
 'Walk in or apply by phone or mail',
 'Walk in or apply by phone or mail']

In [53]:
# convert series to dataframe
s = pd.Series([2, 3, 4], index=[100, "jkmloom", 500])
print(f"Data:\n{s}\nType: {type(s)}")

Data:
100        2
jkmloom    3
500        4
dtype: int64
Type: <class 'pandas.Series'>

In [55]:
# conversion
d = pd.DataFrame(s)
print(f"Dataframe:\n{d}\nType: {type(d)}")

Dataframe:
         0
100      2
jkmloom  3
500      4
Type: <class 'pandas.DataFrame'>

In [56]:
d

         0
100      2
jkmloom  3
500      4

In [57]:
# making a new column in a dataframe
d["new column"] = "jkmloom"
d

         0 new column
100      2    jkmloom
jkmloom  3    jkmloom
500      4    jkmloom

In [59]:
d["custom column"] = ["jkmloom", "jkmcode", "jkmjatin"]
d

         0 new column custom column
100      2    jkmloom       jkmloom
jkmloom  3    jkmloom       jkmcode
500      4    jkmloom      jkmjatin

In [63]:
# new column elements = number of rows/data entry required
d["new_column2"] = [1, 2, 3]
d

         0 new column custom column  new_column2
100      2    jkmloom       jkmloom            1
jkmloom  3    jkmloom       jkmcode            2
500      4    jkmloom      jkmjatin            3

In [64]:
# column names
d.columns

Index([0, 'new column', 'custom column', 'new_column2'], dtype='object')

In [66]:
# update column names
d.columns = ["col1", "col2", "col3", "col4"]
d

         col1     col2      col3  col4
100         2  jkmloom   jkmloom     1
jkmloom     3  jkmloom   jkmcode     2
500         4  jkmloom  jkmjatin     3

In [69]:
# reset index
print(d.reset_index()) # without drop=True
print("***"*14)
print(d.reset_index(drop=True)) # with drop=True

     index  col1     col2      col3  col4
0      100     2  jkmloom   jkmloom     1
1  jkmloom     3  jkmloom   jkmcode     2
2      500     4  jkmloom  jkmjatin     3
******************************************
   col1     col2      col3  col4
0     2  jkmloom   jkmloom     1
1     3  jkmloom   jkmcode     2
2     4  jkmloom  jkmjatin     3

In [70]:
# accessing one column
df["status"]

0       active
1       active
2       active
3       active
4       active
5       active
6       active
7       active
8       active
9       active
10      active
11      active
12      active
13      active
14      active
15      active
16      active
17      active
18      active
19     defunct
20    inactive
21      active
22      active
Name: status, dtype: str

In [75]:
# accessing multiple columns together
# df["status", "languages"] >> this method won't work cause series are 1 dimentional in nature
df_subset = df[["name", "status", "languages"]]
# above method will work cause it's converted to a dataframe using [[douple_paired_square_brackest]]
# aka >> subset of a dataframe
print(df_subset)

                                    name    status languages
0        Fair Oaks Adult Activity Center    active       NaN
1       Second Career Employment Program    active       NaN
2                 Senior Peer Counseling    active       NaN
3               Family Visitation Center    active       NaN
4      Economic Self-Sufficiency Program    active       NaN
5   Little House Recreational Activities    active       NaN
6       Rosener House Adult Day Services    active       NaN
7         Meals on Wheels - South County    active       NaN
8                       Fair Oaks Branch    active       NaN
9                           Main Library    active       NaN
10                       Schaberg Branch    active       NaN
11                          Project Read    active       NaN
12                 Redwood Shores Branch    active       NaN
13                    Redwood City Corps    active       NaN
14           Adult Rehabilitation Center    active       NaN
15                       Sunnyvale Corps    active       NaN
16     South San Francisco Citadel Corps    active       NaN
17                         Project Smile    active       NaN
18         San Mateo Free Medical Clinic    active       NaN
19             Service with blank fields   defunct       NaN
20       Service for Admin Test Location  inactive       NaN
21                       Passport Photos    active   Spanish
22                  Example Service Name    active       NaN

In [77]:
type(df_subset)

pandas.DataFrame

In [ ]:
# reading excel files using pandas
excel_file_path= "../00.1-data/LUSID Excel - Setting up your market data.xlsx"
pd.read_excel(excel_file_path)

FileNotFoundError: [Errno 2] No such file or directory: "../00.1-data/'LUSID Excel - Setting up your market data.xlsx'"