In [1]:
# pandas is a fast, powerful, flexible and easy yo use open source data analysis and manipulartion tool built on top of the pyhton programming language
# pandas was developed in 2008 by Mckinney
# very useful with structured data (eg. tabular data)

In [2]:
import pandas as pd
dataframe_path = "../00.1-data/services.csv"

In [3]:
# reading a cvs (comma separated values) file using pandas
df = pd.read_csv(dataframe_path)
# by default pandas understands the 1st row are column names
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [4]:
# in case if the data has no header (column name)
pd.read_csv(dataframe_path, header = None)
# internal integer indexes are provided by pandas for both rows and columns

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [5]:
# suppose we don't want the first rows
pd.read_csv(dataframe_path, skiprows=2)

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [6]:
# lets say we want to see only 3 columns
pd.read_csv(dataframe_path, usecols=["program_id", "application_process"])

    program_id                                application_process
0          NaN                         Walk in or apply by phone.
1          NaN                 Apply by phone for an appointment.
2          NaN        Phone for information (403-4300 Ext. 4322).
3          NaN                                    Apply by phone.
4          NaN                             Phone for information.
5          NaN  Walk in or apply by phone for membership appli...
6          NaN  Apply by phone or be referred by a doctor, soc...
7          NaN                                    Apply by phone.
8          NaN  Walk in. Proof of residency in California requ...
9          NaN  Walk in. Proof of California residency to rece...
10         NaN  Walk in. Proof of California residency require...
11         NaN  Walk in or apply by phone, email or webpage re...
12         NaN  Walk in. Proof of California residency require...
13         NaN  Call for appointment. Referral from human serv...
14         NaN          Walk in or through other agency referral.
15         NaN  Walk in. Written application, identification r...
16         NaN                              Call for information.
17         NaN  Call for screening appointment. Medical visits...
18         NaN     Call for screening appointment (650-347-3648).
19         NaN                                           Walk in.
20         NaN                    By phone during business hours.
21         NaN                  Walk in or apply by phone or mail
22         NaN                  Walk in or apply by phone or mail

In [7]:
print(pd.read_csv(dataframe_path))

    id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN
1    2            2         NaN                       NaN
2    3            3         NaN                       NaN
3    4            4         NaN                       NaN
4    5            5         NaN                       NaN
5    6            6         NaN                       NaN
6    7            7         NaN                       NaN
7    8            8         NaN                       NaN
8    9            9         NaN                       NaN
9   10           10         NaN                       NaN
10  11           11         NaN                       NaN
11  12           12         NaN                       NaN
12  13           13         NaN                       NaN
13  14           14         NaN                       NaN
14  15           15         NaN                       NaN
15  16           16         NaN                       NaN
16  17           17         NaN                       NaN
17  18           18         NaN                       NaN
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.
1                     NaN                 Apply by phone for an appointment.
2                     NaN        Phone for information (403-4300 Ext. 4322).
3                     NaN                                    Apply by phone.
4                     NaN                             Phone for information.
5                     NaN  Walk in or apply by phone for membership appli...
6                     NaN  Apply by phone or be referred by a doctor, soc...
7                     NaN                                    Apply by phone.
8                     NaN  Walk in. Proof of residency in California requ...
9                     NaN  Walk in. Proof of California residency to rece...
10                    NaN  Walk in. Proof of California residency require...
11                    NaN  Walk in or apply by phone, email or webpage re...
12                    NaN  Walk in. Proof of California residency require...
13                    NaN  Call for appointment. Referral from human serv...
14                    NaN          Walk in or through other agency referral.
15                    NaN  Walk in. Written application, identification r...
16                    NaN                              Call for information.
17                    NaN  Call for screening appointment. Medical visits...
18                    NaN     Call for screening appointment (650-347-3648).
19                    NaN                                           Walk in.
20                    NaN                    By phone during business hours.
21  Fotos para pasaportes                  Walk in or apply by phone or mail
22                    NaN                  Walk in or apply by phone or mail

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...
1        Residents of San Mateo County age 55 or over
2   Older adults age 55 or over who can benefit fr...
3   Parents, children, families with problems of c...
4   Low-income working families with children tran...
5                                             Any age
6   Older adults who have memory or sensory loss, ...
7   Senior citizens age 60 or over, disabled indiv...
8      Ethnic minorities, especially Spanish speaking
9                                                 NaN
10                                                NaN
11  Adults, parents, children in 1st-12th grades i...
12                                                NaN
13  Individuals or families with low or no income ...
14  Adult alcoholic/drug addictive men and women w...
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
0   A walk-in center for older adults that provide...
1   Provides training and job placement to eligibl...
2   Offers supportive counseling services to San M...
3   Provides supervised visitation services and a ...
4   Provides fixed 8% short term loans to eligible...
5   A multipurpose center offering a wide variety ...
6   Rosener House is a day center for older adults...
7   Delivers a hot meal to the home of persons age...
8   Provides general reading material, including b...
9   Provides general reading and media materials, ...
10  Provides general reading materials, including ...
11  Offers an intergenerational literacy program f...
12  Provides general reading materials, including ...
13  Provides food, clothing, bus tokens and shelte...
14  Provides a long-term (6-12 month) residential ...
15  Provides emergency assistance including food a...
16  Provides emergency food, clothing and furnitur...
17  By appointment only, Project Smile provides a ...
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                          eligibility                  email  \
0   Age 55 or over for most programs, age 60 or ov...                    NaN
1   Age 55 or over, county resident and willing an...                    NaN
2         Resident of San Mateo County age 55 or over                    NaN
3                                                 NaN                    NaN
4   Eligibility: Low-income family with legal cust...                    NaN
5                                                 NaN                    NaN
6                                      Age 18 or over                    NaN
7             Homebound person unable to cook or shop                    NaN
8     Resident of California to obtain a library card                    NaN
9             Resident of California to obtain a card                    NaN
10  Resident of California to obtain a library car...                    NaN
11  English-speaking adult reading at or below 7th...                    NaN
12    Resident of California to obtain a library card                    NaN
13  None for most services. For emergency assistan...                    NaN
14  Age 21-60, detoxed, physically able and willin...                    NaN
15                      None for emergency assistance                    NaN
16                                Low-income families                    NaN
17    Low-income person without access to health care                    NaN
18    Low-income person without access to health care                    NaN
19                                                NaN                    NaN
20                                                NaN                    NaN
21                                                NaN  passports@example.org
22                                                NaN                    NaN

    ...                            interpretation_services  \
0   ...                                                NaN
1   ...                                                NaN
2   ...                                                NaN
3   ...                                                NaN
4   ...                                                NaN
5   ...                                                NaN
6   ...                                                NaN
7   ...                                                NaN
8   ...                                                NaN
9   ...                                                NaN
10  ...                                                NaN
11  ...                                                NaN
12  ...                                                NaN
13  ...                                                NaN
14  ...                                                NaN
15  ...                                                NaN
16  ...                                                NaN
17  ...                                                NaN
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN
2   Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN
4      COMMUNITY SERVICES, Speakers, Automobile Loans       NaN
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN
8   EDUCATION SERVICES, Library, Libraries, Public...       NaN
9   EDUCATION SERVICES, Library, Libraries, Public...       NaN
10  EDUCATION SERVICES, Library, Libraries, Public...       NaN
11  EDUCATION SERVICES, Adult, Alternative, Litera...       NaN
12  EDUCATION SERVICES, Library, Libraries, Public...       NaN
13  COMMUNITY SERVICES, Interpretation/Translation...       NaN
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...       NaN
15  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
16  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN
17  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                                    name  \
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

                          required_documents  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  Government-issued picture identification
22                                       NaN

                            service_areas    status  \
0                                   Colma    active
1                        San Mateo County    active
2                        San Mateo County    active
3                        San Mateo County    active
4                        San Mateo County    active
5                        San Mateo County    active
6     Belmont, Burlingame, East Palo Alto    active
7                 Belmont, East Palo Alto    active
8                        San Mateo County    active
9                        San Mateo County    active
10                       San Mateo County    active
11                              Daly City    active
12                       San Mateo County    active
13    Belmont, Burlingame, East Palo Alto    active
14       Alameda County, San Mateo County    active
15                                    NaN    active
16  Colma, Daly City, South San Francisco    active
17                         East Palo Alto    active
18                    Belmont, Burlingame    active
19                                    NaN   defunct
20                       San Mateo County  inactive
21       Alameda County, San Mateo County    active
22       San Mateo County, Alameda County    active

                                            wait_time                 website  \
0                                            No wait.                     NaN
1                                             Varies.                     NaN
2                                             Varies.                     NaN
3                                            No wait.                     NaN
4                                                 NaN                     NaN
5                                            No wait.                     NaN
6                                            No wait.                     NaN
7                                            No wait.                     NaN
8                                            No wait.                     NaN
9                                            No wait.                     NaN
10                                           No wait.                     NaN
11  Depends on availability of tutors for small gr...                     NaN
12                                           No wait.                     NaN
13                                  Up to 20 minutes.                     NaN
14  Varies according to available beds for men and...                     NaN
15                                           No wait.                     NaN
16                                                NaN                     NaN
17                                            Varies.                     NaN
18                                            Varies.                     NaN
19                                                NaN                     NaN
20                                                NaN                     NaN
21                                No wait to 2 weeks.  http://www.example.com
22                                 No wait to 2 weeks  http://www.example.com

                                taxonomy_ids
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
5                                        NaN
6                                        NaN
7                                        NaN
8                                        NaN
9                                        NaN
10                                       NaN
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                       NaN
17                                       NaN
18                                       NaN
19                                       NaN
20                                       NaN
21  105, 108, 108-05, 108-05-01, 111, 111-05
22                                       NaN

[23 rows x 22 columns]

In [8]:
# data structures in pandas >> here data are stored in the form of series and dataframe
# series >> 1 dimentional in nature
# dataframe >> 2 dimentional in nature

In [9]:
# what type is the variable 'df' we were using till now
type(df)

pandas.DataFrame

In [10]:
# access a particular column
df.application_process

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [11]:
# another way to do the same
df["application_process"] # prefered method

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [12]:
# a column of a dataframe is a series
type(df["application_process"])

pandas.Series

In [13]:
lvar = [1, 2, 3, 4]
s = pd.Series(lvar)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [14]:
# we can use slicing techniqe in series just like in a list
print(s[1:])
print(s[2:4])

1    2
2    3
3    4
dtype: int64
2    3
3    4
dtype: int64

In [15]:
# by default the indexes are integer
# but we can have custom indexes
d = pd.Series([100, 200, 300], index = ["jkmloom", "jkmcode", "jkmjatin"])
print(d)

jkmloom     100
jkmcode     200
jkmjatin    300
dtype: int64

In [16]:
type(d)

pandas.Series

In [17]:
# slicing on custom index
d["jkmcode"]

np.int64(200)

In [18]:
# to see all the index of the series
d.index

Index(['jkmloom', 'jkmcode', 'jkmjatin'], dtype='str')

In [19]:
# to reset index
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [20]:
# convert a series into dataframe
pd.DataFrame(d)

            0
jkmloom   100
jkmcode   200
jkmjatin  300

In [21]:
# multiple series combines to form a dataframe 
df_2 = pd.DataFrame(d)
print(f"Dataframe:\n{df_2}\n{"***"*14}\nVariable type: {type(df_2)}")

Dataframe:
            0
jkmloom   100
jkmcode   200
jkmjatin  300
******************************************
Variable type: <class 'pandas.DataFrame'>

In [22]:
# first 5 rows of the datafram
print(df.head())

   id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN
1   2            2         NaN               NaN            NaN
2   3            3         NaN               NaN            NaN
3   4            4         NaN               NaN            NaN
4   5            5         NaN               NaN            NaN

                           application_process  \
0                   Walk in or apply by phone.
1           Apply by phone for an appointment.
2  Phone for information (403-4300 Ext. 4322).
3                              Apply by phone.
4                       Phone for information.

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...
1       Residents of San Mateo County age 55 or over
2  Older adults age 55 or over who can benefit fr...
3  Parents, children, families with problems of c...
4  Low-income working families with children tran...

                                         description  \
0  A walk-in center for older adults that provide...
1  Provides training and job placement to eligibl...
2  Offers supportive counseling services to San M...
3  Provides supervised visitation services and a ...
4  Provides fixed 8% short term loans to eligible...

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...
1  Age 55 or over, county resident and willing an...   NaN  ...
2        Resident of San Mateo County age 55 or over   NaN  ...
3                                                NaN   NaN  ...
4  Eligibility: Low-income family with legal cust...   NaN  ...

  interpretation_services                                           keywords  \
0                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...
1                     NaN  EMPLOYMENT/TRAINING SERVICES, Job Development,...
2                     NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...
3                     NaN  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...
4                     NaN     COMMUNITY SERVICES, Speakers, Automobile Loans

  languages                               name required_documents  \
0       NaN    Fair Oaks Adult Activity Center                NaN
1       NaN   Second Career Employment Program                NaN
2       NaN             Senior Peer Counseling                NaN
3       NaN           Family Visitation Center                NaN
4       NaN  Economic Self-Sufficiency Program                NaN

      service_areas  status wait_time website taxonomy_ids
0             Colma  active  No wait.     NaN          NaN
1  San Mateo County  active   Varies.     NaN          NaN
2  San Mateo County  active   Varies.     NaN          NaN
3  San Mateo County  active  No wait.     NaN          NaN
4  San Mateo County  active       NaN     NaN          NaN

[5 rows x 22 columns]

In [23]:
# last five rows of the dataframe
print(df.tail())

    id  location_id  program_id         accepted_payments  \
18  19           19         NaN                       NaN
19  20           20         NaN                       NaN
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                             application_process  \
18                    NaN  Call for screening appointment (650-347-3648).
19                    NaN                                        Walk in.
20                    NaN                 By phone during business hours.
21  Fotos para pasaportes               Walk in or apply by phone or mail
22                    NaN               Walk in or apply by phone or mail

                                             audience  \
18                                                NaN
19                                                NaN
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description  \
18  Provides free medical and dental care to those...
19              no unrequired fields for this service
20                                just a test service
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...

                                        eligibility                  email  \
18  Low-income person without access to health care                    NaN
19                                              NaN                    NaN
20                                              NaN                    NaN
21                                              NaN  passports@example.org
22                                              NaN                    NaN

    ...                            interpretation_services  \
18  ...                                                NaN
19  ...                                                NaN
20  ...                                                NaN
21  ...  We offer 3-way interpretation services over th...
22  ...                                                NaN

                                             keywords languages  \
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN
19                                                NaN       NaN
20                                                NaN       NaN
21                                    Salud, Medicina   Spanish
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN

                               name                        required_documents  \
18    San Mateo Free Medical Clinic                                       NaN
19        Service with blank fields                                       NaN
20  Service for Admin Test Location                                       NaN
21                  Passport Photos  Government-issued picture identification
22             Example Service Name                                       NaN

                       service_areas    status            wait_time  \
18               Belmont, Burlingame    active              Varies.
19                               NaN   defunct                  NaN
20                  San Mateo County  inactive                  NaN
21  Alameda County, San Mateo County    active  No wait to 2 weeks.
22  San Mateo County, Alameda County    active   No wait to 2 weeks

                   website                              taxonomy_ids
18                     NaN                                       NaN
19                     NaN                                       NaN
20                     NaN                                       NaN
21  http://www.example.com  105, 108, 108-05, 108-05-01, 111, 111-05
22  http://www.example.com                                       NaN

[5 rows x 22 columns]

In [24]:
# defined number of rows from the end
print(df.tail(3)) # defined number here: 3

    id  location_id  program_id         accepted_payments  \
20  21           21         NaN                       NaN
21  22           22         NaN  Cash, Check, Credit Card
22  23           22         NaN                       NaN

           alternate_name                application_process  \
20                    NaN    By phone during business hours.
21  Fotos para pasaportes  Walk in or apply by phone or mail
22                    NaN  Walk in or apply by phone or mail

                                             audience  \
20                                                NaN
21  Profit and nonprofit businesses, the public, m...
22  Second service and nonprofit businesses, the p...

                                          description eligibility  \
20                                just a test service         NaN
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...         NaN
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...         NaN

                    email  ...  \
20                    NaN  ...
21  passports@example.org  ...
22                    NaN  ...

                              interpretation_services  \
20                                                NaN
21  We offer 3-way interpretation services over th...
22                                                NaN

                                      keywords languages  \
20                                         NaN       NaN
21                             Salud, Medicina   Spanish
22  Ruby on Rails/Postgres/Redis, testing, wic       NaN

                               name                        required_documents  \
20  Service for Admin Test Location                                       NaN
21                  Passport Photos  Government-issued picture identification
22             Example Service Name                                       NaN

                       service_areas    status            wait_time  \
20                  San Mateo County  inactive                  NaN
21  Alameda County, San Mateo County    active  No wait to 2 weeks.
22  San Mateo County, Alameda County    active   No wait to 2 weeks

                   website                              taxonomy_ids
20                     NaN                                       NaN
21  http://www.example.com  105, 108, 108-05, 108-05-01, 111, 111-05
22  http://www.example.com                                       NaN

[3 rows x 22 columns]

In [25]:
# shape (number of columns and rows) of the dataframe
print(f"Dataframe shape: {df.shape}")

Dataframe shape: (23, 22)

In [26]:
# columns of a dataframe
print(df.columns)

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [27]:
# convert the columns into a list
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [28]:
# see a randow row from the dataframe
df.sample() # default: returns 1 value

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN

In [29]:
# defined number of random rows from a dataframe
print(df.sample(3))

    id  location_id  program_id accepted_payments alternate_name  \
2    3            3         NaN               NaN            NaN
15  16           16         NaN               NaN            NaN
8    9            9         NaN               NaN            NaN

                                  application_process  \
2         Phone for information (403-4300 Ext. 4322).
15  Walk in. Written application, identification r...
8   Walk in. Proof of residency in California requ...

                                             audience  \
2   Older adults age 55 or over who can benefit fr...
15                                                NaN
8      Ethnic minorities, especially Spanish speaking

                                          description  \
2   Offers supportive counseling services to San M...
15  Provides emergency assistance including food a...
8   Provides general reading material, including b...

                                        eligibility email  ...  \
2       Resident of San Mateo County age 55 or over   NaN  ...
15                    None for emergency assistance   NaN  ...
8   Resident of California to obtain a library card   NaN  ...

   interpretation_services                                           keywords  \
2                      NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...
15                     NaN  COMMODITY SERVICES, Clothing/Personal Items, C...
8                      NaN  EDUCATION SERVICES, Library, Libraries, Public...

   languages                    name required_documents     service_areas  \
2        NaN  Senior Peer Counseling                NaN  San Mateo County
15       NaN         Sunnyvale Corps                NaN               NaN
8        NaN        Fair Oaks Branch                NaN  San Mateo County

    status wait_time website taxonomy_ids
2   active   Varies.     NaN          NaN
15  active  No wait.     NaN          NaN
8   active  No wait.     NaN          NaN

[3 rows x 22 columns]

In [30]:
# check infromation about the dataframe in pandas
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      str
 4   alternate_name           1 non-null      str
 5   application_process      23 non-null     str
 6   audience                 14 non-null     str
 7   description              23 non-null     str
 8   eligibility              17 non-null     str
 9   email                    1 non-null      str
 10  fees                     21 non-null     str
 11  funding_sources          21 non-null     str
 12  interpretation_services  1 non-null      str
 13  keywords                 21 non-null     str
 14  languages                1 non-null      str
 15  name                     23 non-null     str
 16  required_documents       1 non-null      str
 17  service_areas            21 non-null     str
 18  status                   23 non-null     str
 19  wait_time                19 non-null     str
 20  website                  2 non-null      str
 21  taxonomy_ids             1 non-null      str
dtypes: float64(1), int64(2), str(19)
memory usage: 4.1 KB

In [31]:
# check data types in a dataframe
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [32]:
# revise: dataframe is a collection of series
print(type(df['id']))

<class 'pandas.Series'>

In [33]:
type(df["application_process"])

pandas.Series

In [34]:
list(df["application_process"])

['Walk in or apply by phone.',
 'Apply by phone for an appointment.',
 'Phone for information (403-4300 Ext. 4322).',
 'Apply by phone.',
 'Phone for information.',
 'Walk in or apply by phone for membership application.',
 'Apply by phone or be referred by a doctor, social worker or other professional. All prospective participants are interviewed individually before starting the program. A recent physical examination is required, including a TB test.',
 'Apply by phone.',
 'Walk in. Proof of residency in California required to receive a library card.',
 'Walk in. Proof of California residency to receive a library card.',
 'Walk in. Proof of California residency required to receive a library card.',
 'Walk in or apply by phone, email or webpage registration.',
 'Walk in. Proof of California residency required to receive a library card.',
 'Call for appointment. Referral from human service professional preferred for emergency assistance.',
 'Walk in or through other agency referral.',
 'Walk in. Written application, identification required for emergency assistance.',
 'Call for information.',
 'Call for screening appointment. Medical visits are by appointment only.',
 'Call for screening appointment (650-347-3648).',
 'Walk in.',
 'By phone during business hours.',
 'Walk in or apply by phone or mail',
 'Walk in or apply by phone or mail']

In [35]:
# convert series to dataframe
s = pd.Series([2, 3, 4], index=[100, "jkmloom", 500])
print(f"Data:\n{s}\nType: {type(s)}")

Data:
100        2
jkmloom    3
500        4
dtype: int64
Type: <class 'pandas.Series'>

In [36]:
# conversion
d = pd.DataFrame(s)
print(f"Dataframe:\n{d}\nType: {type(d)}")

Dataframe:
         0
100      2
jkmloom  3
500      4
Type: <class 'pandas.DataFrame'>

In [37]:
d

         0
100      2
jkmloom  3
500      4

In [38]:
# making a new column in a dataframe
d["new column"] = "jkmloom"
d

         0 new column
100      2    jkmloom
jkmloom  3    jkmloom
500      4    jkmloom

In [39]:
d["custom column"] = ["jkmloom", "jkmcode", "jkmjatin"]
d

         0 new column custom column
100      2    jkmloom       jkmloom
jkmloom  3    jkmloom       jkmcode
500      4    jkmloom      jkmjatin

In [40]:
# new column elements = number of rows/data entry required
d["new_column2"] = [1, 2, 3]
d

         0 new column custom column  new_column2
100      2    jkmloom       jkmloom            1
jkmloom  3    jkmloom       jkmcode            2
500      4    jkmloom      jkmjatin            3

In [41]:
# column names
d.columns

Index([0, 'new column', 'custom column', 'new_column2'], dtype='object')

In [42]:
# update column names
d.columns = ["col1", "col2", "col3", "col4"]
d

         col1     col2      col3  col4
100         2  jkmloom   jkmloom     1
jkmloom     3  jkmloom   jkmcode     2
500         4  jkmloom  jkmjatin     3

In [43]:
# reset index
print(d.reset_index()) # without drop=True
print("***"*14)
print(d.reset_index(drop=True)) # with drop=True

     index  col1     col2      col3  col4
0      100     2  jkmloom   jkmloom     1
1  jkmloom     3  jkmloom   jkmcode     2
2      500     4  jkmloom  jkmjatin     3
******************************************
   col1     col2      col3  col4
0     2  jkmloom   jkmloom     1
1     3  jkmloom   jkmcode     2
2     4  jkmloom  jkmjatin     3

In [44]:
# accessing one column
df["status"]

0       active
1       active
2       active
3       active
4       active
5       active
6       active
7       active
8       active
9       active
10      active
11      active
12      active
13      active
14      active
15      active
16      active
17      active
18      active
19     defunct
20    inactive
21      active
22      active
Name: status, dtype: str

In [45]:
# accessing multiple columns together
# df["status", "languages"] >> this method won't work cause series are 1 dimentional in nature
df_subset = df[["name", "status", "languages"]]
# above method will work cause it's converted to a dataframe using [[douple_paired_square_brackest]]
# aka >> subset of a dataframe
print(df_subset)

                                    name    status languages
0        Fair Oaks Adult Activity Center    active       NaN
1       Second Career Employment Program    active       NaN
2                 Senior Peer Counseling    active       NaN
3               Family Visitation Center    active       NaN
4      Economic Self-Sufficiency Program    active       NaN
5   Little House Recreational Activities    active       NaN
6       Rosener House Adult Day Services    active       NaN
7         Meals on Wheels - South County    active       NaN
8                       Fair Oaks Branch    active       NaN
9                           Main Library    active       NaN
10                       Schaberg Branch    active       NaN
11                          Project Read    active       NaN
12                 Redwood Shores Branch    active       NaN
13                    Redwood City Corps    active       NaN
14           Adult Rehabilitation Center    active       NaN
15                       Sunnyvale Corps    active       NaN
16     South San Francisco Citadel Corps    active       NaN
17                         Project Smile    active       NaN
18         San Mateo Free Medical Clinic    active       NaN
19             Service with blank fields   defunct       NaN
20       Service for Admin Test Location  inactive       NaN
21                       Passport Photos    active   Spanish
22                  Example Service Name    active       NaN

In [46]:
type(df_subset)

pandas.DataFrame

In [47]:
# reading excel files using pandas
excel_file_path= "../00.1-data/LUSID Excel - Setting up your market data.xlsx"
pd.read_excel(excel_file_path)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaN,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaN,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,2019-04-10 00:00:00,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,13:30:45.550000,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,2019-04-10 13:30:45.550000,NaN,Cutlabel,2019-04-10NSingaporeClose,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [48]:
# opeerations are mostly gonna be same
df1 = pd.read_excel(excel_file_path)

In [49]:
df.shape

(23, 22)

In [50]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      str
 4   alternate_name           1 non-null      str
 5   application_process      23 non-null     str
 6   audience                 14 non-null     str
 7   description              23 non-null     str
 8   eligibility              17 non-null     str
 9   email                    1 non-null      str
 10  fees                     21 non-null     str
 11  funding_sources          21 non-null     str
 12  interpretation_services  1 non-null      str
 13  keywords                 21 non-null     str
 14  languages                1 non-null      str
 15  name                     23 non-null     str
 16  required_documents       1 non-null      str
 17  service_areas            21 non-null     str
 18  status                   23 non-null     str
 19  wait_time                19 non-null     str
 20  website                  2 non-null      str
 21  taxonomy_ids             1 non-null      str
dtypes: float64(1), int64(2), str(19)
memory usage: 4.1 KB

In [52]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [53]:
# reading another csv file
taxonomy = "../00.1-data/taxonomy.csv"
another_df = pd.read_csv(taxonomy)
print(another_df)

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [54]:
# reading csv/data from a file online
df3 = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [55]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [56]:
df3.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [57]:
df3.shape

(891, 12)

In [58]:
df3.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [59]:
print(df3.Sex) # or
print("***"*15)
print(df3["Sex"]) # prefered method

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str
*********************************************
0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [60]:
# subset of the dataframe
df3[["PassengerId", "Name", "Sex"]]

     PassengerId                                               Name     Sex
0              1                            Braund, Mr. Owen Harris    male
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2              3                             Heikkinen, Miss. Laina  female
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4              5                           Allen, Mr. William Henry    male
..           ...                                                ...     ...
886          887                              Montvila, Rev. Juozas    male
887          888                       Graham, Miss. Margaret Edith  female
888          889           Johnston, Miss. Catherine Helen "Carrie"  female
889          890                              Behr, Mr. Karl Howell    male
890          891                                Dooley, Mr. Patrick    male

[891 rows x 3 columns]

In [21]:
# reading html file onlint using pandas

In [16]:
df4 = pd.read_html("http://www.contextures.com/xlSampleData01.html")
print(df4)

[                                                   0  \
0  Home > Data > Sample > Sample Data Excel Sampl...
1                                                NaN

                                                   1
0                                                NaN
1  Get this Microsoft Excel sample data for pract...  ,     0                                                  1
0 NaN  Get this Microsoft Excel sample data for pract...,              0        1         2        3      4         5        6
0    OrderDate   Region       Rep     Item  Units  UnitCost    Total
1     1/6/2024     East     Jones   Pencil     95      1.99   189.05
2    1/23/2024  Central    Kivell   Binder     50     19.99   999.50
3     2/9/2024  Central   Jardine   Pencil     36      4.99   179.64
4    2/26/2024  Central      Gill      Pen     27     19.99   539.73
5    3/15/2024     West   Sorvino   Pencil     56      2.99   167.44
6     4/1/2024     East     Jones   Binder     60      4.99   299.40
7    4/18/2024  Central   Andrews   Pencil     75      1.99   149.25
8     5/5/2024  Central   Jardine   Pencil     90      4.99   449.10
9    5/22/2024     West  Thompson   Pencil     32      1.99    63.68
10    6/8/2024     East     Jones   Binder     60      8.99   539.40
11   6/25/2024  Central    Morgan   Pencil     90      4.99   449.10
12   7/12/2024     East    Howard   Binder     29      1.99    57.71
13   7/29/2024     East    Parent   Binder     81     19.99  1619.19
14   8/15/2024     East     Jones   Pencil     35      4.99   174.65
15    9/1/2024  Central     Smith     Desk      2    125.00   250.00
16   9/18/2024     East     Jones  Pen Set     16     15.99   255.84
17   10/5/2024  Central    Morgan   Binder     28      8.99   251.72
18  10/22/2024     East     Jones      Pen     64      8.99   575.36
19   11/8/2024     East    Parent      Pen     15     19.99   299.85
20  11/25/2024  Central    Kivell  Pen Set     96      4.99   479.04
21  12/12/2024  Central     Smith   Pencil     67      1.29    86.43
22  12/29/2024     East    Parent  Pen Set     74     15.99  1183.26
23   1/15/2025  Central      Gill   Binder     46      8.99   413.54
24    2/1/2025  Central     Smith   Binder     87     15.00  1305.00
25   2/18/2025     East     Jones   Binder      4      4.99    19.96
26    3/7/2025     West   Sorvino   Binder      7     19.99   139.93
27   3/24/2025  Central   Jardine  Pen Set     50      4.99   249.50
28   4/10/2025  Central   Andrews   Pencil     66      1.99   131.34
29   4/27/2025     East    Howard      Pen     96      4.99   479.04
30   5/14/2025  Central      Gill   Pencil     53      1.29    68.37
31   5/31/2025  Central      Gill   Binder     80      8.99   719.20
32   6/17/2025  Central    Kivell     Desk      5    125.00   625.00
33    7/4/2025     East     Jones  Pen Set     62      4.99   309.38
34   7/21/2025  Central    Morgan  Pen Set     55     12.49   686.95
35    8/7/2025  Central    Kivell  Pen Set     42     23.95  1005.90
36   8/24/2025     West   Sorvino     Desk      3    275.00   825.00
37   9/10/2025  Central      Gill   Pencil      7      1.29     9.03
38   9/27/2025     West   Sorvino      Pen     76      1.99   151.24
39  10/14/2025     West  Thompson   Binder     57     19.99  1139.43
40  10/31/2025  Central   Andrews   Pencil     14      1.29    18.06
41  11/17/2025  Central   Jardine   Binder     11      4.99    54.89
42   12/4/2025  Central   Jardine   Binder     94     19.99  1879.06
43  12/21/2025  Central   Andrews   Binder     28      4.99   139.72,     0                                                  1
0 NaN  Food Sales - This sample Excel file has food s...,     0                                                  1
0 NaN  Athlete Data - These sample Excel files have d...,     0                                                  1
0 NaN  Hockey Player Data - This sample file has data...,     0                                                  1
0 NaN  Workplace Safety Data: This sample file has da...,     0                                                  1
0 NaN  Work Orders Data: This sample file has data fo...,     0                                                  1
0 NaN  Insurance Policies: This sample file has comme...,     0                                                  1
0 NaN  Food Nutrients: This sample file has food nutr...]

In [17]:
df4

[                                                   0  \
 0  Home > Data > Sample > Sample Data Excel Sampl...
 1                                                NaN

                                                    1
 0                                                NaN
 1  Get this Microsoft Excel sample data for pract...  ,
     0                                                  1
 0 NaN  Get this Microsoft Excel sample data for pract...,
              0        1         2        3      4         5        6
 0    OrderDate   Region       Rep     Item  Units  UnitCost    Total
 1     1/6/2024     East     Jones   Pencil     95      1.99   189.05
 2    1/23/2024  Central    Kivell   Binder     50     19.99   999.50
 3     2/9/2024  Central   Jardine   Pencil     36      4.99   179.64
 4    2/26/2024  Central      Gill      Pen     27     19.99   539.73
 5    3/15/2024     West   Sorvino   Pencil     56      2.99   167.44
 6     4/1/2024     East     Jones   Binder     60      4.99   299.40
 7    4/18/2024  Central   Andrews   Pencil     75      1.99   149.25
 8     5/5/2024  Central   Jardine   Pencil     90      4.99   449.10
 9    5/22/2024     West  Thompson   Pencil     32      1.99    63.68
 10    6/8/2024     East     Jones   Binder     60      8.99   539.40
 11   6/25/2024  Central    Morgan   Pencil     90      4.99   449.10
 12   7/12/2024     East    Howard   Binder     29      1.99    57.71
 13   7/29/2024     East    Parent   Binder     81     19.99  1619.19
 14   8/15/2024     East     Jones   Pencil     35      4.99   174.65
 15    9/1/2024  Central     Smith     Desk      2    125.00   250.00
 16   9/18/2024     East     Jones  Pen Set     16     15.99   255.84
 17   10/5/2024  Central    Morgan   Binder     28      8.99   251.72
 18  10/22/2024     East     Jones      Pen     64      8.99   575.36
 19   11/8/2024     East    Parent      Pen     15     19.99   299.85
 20  11/25/2024  Central    Kivell  Pen Set     96      4.99   479.04
 21  12/12/2024  Central     Smith   Pencil     67      1.29    86.43
 22  12/29/2024     East    Parent  Pen Set     74     15.99  1183.26
 23   1/15/2025  Central      Gill   Binder     46      8.99   413.54
 24    2/1/2025  Central     Smith   Binder     87     15.00  1305.00
 25   2/18/2025     East     Jones   Binder      4      4.99    19.96
 26    3/7/2025     West   Sorvino   Binder      7     19.99   139.93
 27   3/24/2025  Central   Jardine  Pen Set     50      4.99   249.50
 28   4/10/2025  Central   Andrews   Pencil     66      1.99   131.34
 29   4/27/2025     East    Howard      Pen     96      4.99   479.04
 30   5/14/2025  Central      Gill   Pencil     53      1.29    68.37
 31   5/31/2025  Central      Gill   Binder     80      8.99   719.20
 32   6/17/2025  Central    Kivell     Desk      5    125.00   625.00
 33    7/4/2025     East     Jones  Pen Set     62      4.99   309.38
 34   7/21/2025  Central    Morgan  Pen Set     55     12.49   686.95
 35    8/7/2025  Central    Kivell  Pen Set     42     23.95  1005.90
 36   8/24/2025     West   Sorvino     Desk      3    275.00   825.00
 37   9/10/2025  Central      Gill   Pencil      7      1.29     9.03
 38   9/27/2025     West   Sorvino      Pen     76      1.99   151.24
 39  10/14/2025     West  Thompson   Binder     57     19.99  1139.43
 40  10/31/2025  Central   Andrews   Pencil     14      1.29    18.06
 41  11/17/2025  Central   Jardine   Binder     11      4.99    54.89
 42   12/4/2025  Central   Jardine   Binder     94     19.99  1879.06
 43  12/21/2025  Central   Andrews   Binder     28      4.99   139.72,
     0                                                  1
 0 NaN  Food Sales - This sample Excel file has food s...,
     0                                                  1
 0 NaN  Athlete Data - These sample Excel files have d...,
     0                                                  1
 0 NaN  Hockey Player Data - This sample file has data...,
     0                                                  1
 0 NaN  Workplace Safety Data: This sample file has da...,
     0                                                  1
 0 NaN  Work Orders Data: This sample file has data fo...,
     0                                                  1
 0 NaN  Insurance Policies: This sample file has comme...,
     0                                                  1
 0 NaN  Food Nutrients: This sample file has food nutr...]

In [20]:
type(df4)

list

i could not find an url to a html file (that could be accessed simply in one line of code) so i used an url to a list file instead.  
hence, some functions/operations could not be performed that you may expect from a normal html file.

In [23]:
df4.to_csv("../00.1-data/html_data_reading.csv", index=False)
# index=False >> we dont want the index to be entered in the csv file cause csv creates index on it's own

AttributeError: 'list' object has no attribute 'to_csv'

In [25]:
# reading online json file using pandas
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
pd.read_json(url)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,pull_request,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason,sub_issues_summary,issue_dependencies_summary,pinned_comment
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64412,4029361259,PR_kwDOAA0YD87IQn8v,64412,DOC: fix dtype dict examples in read_csv/read_...,...,{'url': 'https://api.github.com/repos/pandas-d...,## Summary\r\n- fixes the `dtype` dict example...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64411,4027938461,PR_kwDOAA0YD87IL3mn,64411,ERR: Better error message for convert_dtypes w...,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #63745\n\n## Summary\nProvide a clear er...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64410,4027927334,PR_kwDOAA0YD87IL1SO,64410,BUG: Fix to_datetime scalar out of bounds with...,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #60677\n\n## Summary\nFix pd.to_datetime...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64409,4027910222,PR_kwDOAA0YD87ILxqW,64409,BUG: Fix str.find to return character indices ...,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #64123\n\n## Summary\nFix Series.str.fin...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64408,4027894267,PR_kwDOAA0YD87ILuSr,64408,BUG: Reject multidimensional arrays in pd.arra...,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #64280\n\n## Summary\nFix pd.array to pr...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64407,4027774871,PR_kwDOAA0YD87ILU_J,64407,TST: Add regression test for GH#27437,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #27437\n\nAdd regression test for indexi...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64406,4027769855,PR_kwDOAA0YD87ILT6U,64406,TST: Add regression test for GH#29576,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #29576\n\nAdd regression test to ensure ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64405,4027765270,PR_kwDOAA0YD87ILS8S,64405,TST: Add regression test for GH#31142,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #31142\n\nAdd regression test for Series...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64404,4027760585,PR_kwDOAA0YD87ILR74,64404,TST: Add regression test for GH#33992,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #33992\n\nAdd regression test to ensure ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64403,4027752849,PR_kwDOAA0YD87ILQQ6,64403,TST: Add regression test for GH#53307,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #53307\n\nAdd regression test to ensure ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64402,4027747704,PR_kwDOAA0YD87ILPKM,64402,TST: Add regression test for GH#54627,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #54627\n\nAdd regression test to ensure ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64401,4027742016,PR_kwDOAA0YD87ILN62,64401,TST: Add regression test for GH#55136,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #55136\n\nAdd regression test for dt.to_...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64400,4027724951,PR_kwDOAA0YD87ILKOA,64400,TST: Add regression test for GH#57702,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #57702\n\nAdd regression test to ensure ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64399,4027719761,PR_kwDOAA0YD87ILJFY,64399,TST: Add regression test for GH#55969,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #55969\n\nAdd regression test for MultiI...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64398,4027710707,PR_kwDOAA0YD87ILHHr,64398,TST: Add regression test for GH#55423,...,{'url': 'https://api.github.com/repos/pandas-d...,Fixes #55423\n\nAdd regression test to ensure ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64397,4027636505,PR_kwDOAA0YD87IK3JR,64397,BUG: fix IntervalDtype.__from_arrow__ for null...,...,{'url': 'https://api.github.com/repos/pandas-d...,## Summary\n- fix `IntervalDtype.__from_arrow_...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64396,4025696891,PR_kwDOAA0YD87IEXRM,64396,CI: CI/CD hardening,...,{'url': 'https://api.github.com/repos/pandas-d...,Inspired by recent CI attacks: https://www.ste...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64395,4025275141,I_kwDOAA0YD87v7NMF,64395,DEPR: float_precision in read_csv,...,NaN,"We have ""high"" (the default), ""legacy"", and ""r...",NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64394,4024019462,I_kwDOAA0YD87v2aoG,64394,DOC: Example of a `dict` for the `dtype` argum...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64393,4022559717,I_kwDOAA0YD87vw2Pl,64393,BUG: error when summing string to `pa.large_st...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64392,4022144054,PR_kwDOAA0YD87H4rtx,64392,BUG: prevent precision loss in to_numeric for ...,...,{'url': 'https://api.github.com/repos/pandas-d...,Closes #64184\r\n\r\nFix precision loss in pd....,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64391,4022028526,I_kwDOAA0YD87vu0ju,64391,BUG: `eval` not working with string containment,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64390,4020816773,PR_kwDOAA0YD87H0UhQ,64390,BUG: Prevent DataFrame.to_sql() from overridin...,...,{'url': 'https://api.github.com/repos/pandas-d...,\r\n- [x] closes #xxxx (Replace xxxx with the ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64388,4018978437,PR_kwDOAA0YD87HubFF,64388,REGR/PERF: Fix perf regression in _LocationInd...,...,{'url': 'https://api.github.com/repos/pandas-d...,Ref: https://github.com/pandas-dev/pandas/pull...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64387,4018612782,PR_kwDOAA0YD87HtRar,64387,BUG: fix sort_index with level keyword on sing...,...,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #64383\r\n- [ ] [Tests added and ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64386,4018583852,PR_kwDOAA0YD87HtLTc,64386,BUG: fix sort_index AssertionError with RangeI...,...,{'url': 'https://api.github.com/repos/pandas-d...,closes #64383\n\n`RangeIndex.sort_values(retur...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64383,4016615667,I_kwDOAA0YD87vaLDz,64383,BUG: DataFrame.sort_index does fails with `Ass...,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/64381,4015837071,I_kwDOAA0YD87vXM-P,64381,DOC: Typo in Cheatsheet regarding df.dtypes,...,NaN,### Pandas version checks\n\n- [x] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,"{'total': 0, 'completed': 0, 'percent_complete...","{'blocked_by': 0, 'total_blocked_by': 0, 'bloc...",NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64379,4015369336,PR_kwDOAA0YD87HiokY,64379,PERF: datetime index getters functions are 10 ...,...,{'url': 'https://api.github.com/repos/pandas-d...,\r\n\r\n- [x] closes #64363 (Replace xxxx with...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/64377,4015105383,PR_kwDOAA0YD87HhyBD,64377,PERF: Speed up DatetimeIndex field accessors w...,...,{'url': 'https://api.github.com/repos/pandas-d...,## Summary\n\n- Routes ZoneInfo timezones thro...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN,NaN

In [26]:
import requests
data = requests.get(url)

In [27]:
data

In [28]:
data.json()

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64412',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64412/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64412/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64412/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64412',
  'id': 4029361259,
  'node_id': 'PR_kwDOAA0YD87IQn8v',
  'number': 64412,
  'title': 'DOC: fix dtype dict examples in read_csv/read_table',
  'user': {'login': 'mitre88',
   'id': 30060514,
   'node_id': 'MDQ6VXNlcjMwMDYwNTE0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/30060514?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mitre88',
   'html_url': 'https://github.com/mitre88',
   'followers_url': 'https://api.github.com/users/mitre88/followers',
   'following_url': 'https://api.github.com/users/mitre88/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mitre88/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mitre88/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mitre88/subscriptions',
   'organizations_url': 'https://api.github.com/users/mitre88/orgs',
   'repos_url': 'https://api.github.com/users/mitre88/repos',
   'events_url': 'https://api.github.com/users/mitre88/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mitre88/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-03-05T16:33:45Z',
  'updated_at': '2026-03-05T16:33:45Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64412',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64412',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64412.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64412.patch',
   'merged_at': None},
  'body': '## Summary\r\n- fixes the `dtype` dict example in `read_csv` docstring\r\n- applies the same fix to the equivalent `read_table` example for consistency\r\n\r\n## Details\r\n- changed `dtype={{"Value": float}}` to `dtype={"Value": float}` in:\r\n  - `pandas/io/parsers/readers.py` (`read_csv`)\r\n  - `pandas/io/parsers/readers.py` (`read_table`)\r\n\r\n- [x] closes #64394\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n- [x] I have reviewed and followed all the [contribution guidelines](https://pandas.pydata.org/docs/dev/development/contributing.html)\r\n- [x] If I used AI to develop this pull request, I prompted it to follow `AGENTS.md`.',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64412/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64412/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64411',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64411/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64411/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64411/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64411',
  'id': 4027938461,
  'node_id': 'PR_kwDOAA0YD87IL3mn',
  'number': 64411,
  'title': 'ERR: Better error message for convert_dtypes without pyarrow (GH#63745)',
  'user': {'login': 'Simon99',
   'id': 7273055,
   'node_id': 'MDQ6VXNlcjcyNzMwNTU=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7273055?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Simon99',
   'html_url': 'https://github.com/Simon99',
   'followers_url': 'https://api.github.com/users/Simon99/followers',
   'following_url': 'https://api.github.com/users/Simon99/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Simon99/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Simon99/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Simon99/subscriptions',
   'organizations_url': 'https://api.github.com/users/Simon99/orgs',
   'repos_url': 'https://api.github.com/users/Simon99/repos',
   'events_url': 'https://api.github.com/users/Simon99/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Simon99/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-03-05T12:31:18Z',
  'updated_at': '2026-03-05T12:31:18Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64411',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64411',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64411.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64411.patch',
   'merged_at': None},
  'body': 'Fixes #63745\n\n## Summary\nProvide a clear error message when `convert_dtypes(dtype_backend=\'pyarrow\')` is called without pyarrow installed.\n\n## Background\nWhen pyarrow was not installed, calling `convert_dtypes(dtype_backend=\'pyarrow\')` raised a cryptic error deep in the conversion process:\n\n```python\nNameError: name \'ArrowDtype\' is not defined\n```\n\nThis occurred when trying to check `isinstance(dtype, ArrowDtype)`, but `ArrowDtype` wasn\'t imported because pyarrow was missing.\n\n## Changes\n- Added pyarrow availability check in `check_dtype_backend()`\n- Now raises a clear `ImportError` early with helpful message:\n  ```\n  ImportError: dtype_backend=\'pyarrow\' requires the \'pyarrow\' package.\n  Use pip or conda to install the pyarrow package.\n  ```\n\n## Testing\nAdded `test_convert_dtypes_pyarrow_not_installed_error`:\n- Uses monkeypatch to simulate missing pyarrow\n- Verifies clear ImportError is raised with helpful message\n\n## Before/After\n**Before:**\n```python\ndf.convert_dtypes(dtype_backend="pyarrow")\n# NameError: name \'ArrowDtype\' is not defined  ❌ Cryptic!\n```\n\n**After:**\n```python\ndf.convert_dtypes(dtype_backend="pyarrow")\n# ImportError: dtype_backend=\'pyarrow\' requires the \'pyarrow\' package.  ✓ Clear!\n```\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64411/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64411/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64410',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64410/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64410/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64410/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64410',
  'id': 4027927334,
  'node_id': 'PR_kwDOAA0YD87IL1SO',
  'number': 64410,
  'title': 'BUG: Fix to_datetime scalar out of bounds with unit (GH#60677)',
  'user': {'login': 'Simon99',
   'id': 7273055,
   'node_id': 'MDQ6VXNlcjcyNzMwNTU=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7273055?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Simon99',
   'html_url': 'https://github.com/Simon99',
   'followers_url': 'https://api.github.com/users/Simon99/followers',
   'following_url': 'https://api.github.com/users/Simon99/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Simon99/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Simon99/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Simon99/subscriptions',
   'organizations_url': 'https://api.github.com/users/Simon99/orgs',
   'repos_url': 'https://api.github.com/users/Simon99/repos',
   'events_url': 'https://api.github.com/users/Simon99/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Simon99/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-03-05T12:28:53Z',
  'updated_at': '2026-03-05T13:06:42Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64410',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64410',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64410.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64410.patch',
   'merged_at': None},
  'body': 'Fixes #60677\n\n## Summary\nFix pd.to_datetime to raise OutOfBoundsDatetime for scalar out-of-bounds inputs when unit parameter is specified, matching the behavior for list inputs.\n\n## Background\npd.to_datetime was inconsistent in handling out-of-bounds values:\n\n```python\nuint64_max = np.iinfo("uint64").max\n\n# List input correctly raised OutOfBoundsDatetime\npd.to_datetime([uint64_max], unit="ns")  # ✓ Raises\n\n# Scalar input silently wrapped around (BUG)\npd.to_datetime(uint64_max, unit="ns")   # ✗ Returns 1969-12-31\n```\n\n## Root Cause\nIn `_to_datetime_with_unit`, the code did:\n```python\narr = arg.astype(f"datetime64[{unit}]", copy=False)  # ← Wraps around on overflow!\n```\n\nNumPy\'s `astype` wraps around on integer overflow instead of raising an error. For `uint64_max`, this produced `1969-12-31` instead of detecting the overflow.\n\n## Fix\n- Convert integer arrays to `int64` before datetime conversion\n- Use `astype_overflowsafe` directly, which properly detects overflow\n- Ensures `OutOfBoundsDatetime` is raised consistently for both scalar and array inputs\n\n## Testing\n```python\nuint64_max = np.iinfo("uint64").max\n\n# Both now raise OutOfBoundsDatetime\npd.to_datetime(uint64_max, unit="ns")      # Raises\npd.to_datetime([uint64_max], unit="ns")    # Raises\n\n# Both handle errors=\'coerce\' consistently\npd.to_datetime(uint64_max, unit="ns", errors="coerce")      # NaT\npd.to_datetime([uint64_max], unit="ns", errors="coerce")    # [NaT]\n```\n\nAdded comprehensive tests in `test_to_datetime_scalar_out_of_bounds_with_unit`.\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64410/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64410/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64409',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64409/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64409/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64409/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64409',
  'id': 4027910222,
  'node_id': 'PR_kwDOAA0YD87ILxqW',
  'number': 64409,
  'title': 'BUG: Fix str.find to return character indices for Arrow strings (GH#64123)',
  'user': {'login': 'Simon99',
   'id': 7273055,
   'node_id': 'MDQ6VXNlcjcyNzMwNTU=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7273055?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Simon99',
   'html_url': 'https://github.com/Simon99',
   'followers_url': 'https://api.github.com/users/Simon99/followers',
   'following_url': 'https://api.github.com/users/Simon99/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Simon99/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Simon99/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Simon99/subscriptions',
   'organizations_url': 'https://api.github.com/users/Simon99/orgs',
   'repos_url': 'https://api.github.com/users/Simon99/repos',
   'events_url': 'https://api.github.com/users/Simon99/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Simon99/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-03-05T12:25:09Z',
  'updated_at': '2026-03-05T13:02:58Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64409',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64409',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64409.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64409.patch',
   'merged_at': None},
  'body': "Fixes #64123\n\n## Summary\nFix Series.str.find() to return character indices instead of byte indices when using Arrow string dtype.\n\n## Background\nPyArrow's `pc.find_substring()` returns byte offsets within UTF-8 encoded strings, but Python's `str.find()` returns character positions. This caused incorrect results for strings containing multibyte UTF-8 characters:\n\n```python\n# Python (correct):\n'Áa'.find('a')  # Returns 1 (character index)\n\n# pandas with dtype=str (incorrect before fix):\npd.Series(['Áa'], dtype=str).str.find('a')  # Returned 2 (byte index)\n```\n\nThe character `Á` is one character but takes 2 bytes in UTF-8. Similarly, `永` takes 3 bytes, and `🐍` takes 4 bytes.\n\n## Changes\n- Modified `_str_find()` in `pandas/core/arrays/_arrow_string_mixins.py` to use element-wise Python `str.find()`\n- This ensures character-based indexing consistent with Python's behavior\n- Added comprehensive tests for ASCII, 2-byte, 3-byte, and 4-byte UTF-8 characters\n- Tests verify both simple find and find with start/end parameters\n\n## Performance Note\nThis changes from vectorized PyArrow operations to element-wise Python calls. The correctness gain outweighs the performance cost for typical use cases. If performance becomes an issue, a more sophisticated byte-to-character index conversion using PyArrow primitives could be implemented.\n\n## Testing\n```python\nimport pandas as pd\n\nexamples = ['ga', 'Áa', '永a', '🐍a']\n\nfor text in examples:\n    s = pd.Series([text], dtype=str)\n    char_index = s.str.find('a')[0]\n    expected = text.find('a')\n    assert char_index == expected == 1  # All should return 1\n```\n\nAll tests pass, verifying that `str.find()` now returns character indices correctly.\n",
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64409/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64409/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64408',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64408/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64408/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/64408/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/64408',
  'id': 4027894267,
  'node_id': 'PR_kwDOAA0YD87ILuSr',
  'number': 64408,
  'title': 'BUG: Reject multidimensional arrays in pd.array (GH#64280)',
  'user': {'login': 'Simon99',
   'id': 7273055,
   'node_id': 'MDQ6VXNlcjcyNzMwNTU=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7273055?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Simon99',
   'html_url': 'https://github.com/Simon99',
   'followers_url': 'https://api.github.com/users/Simon99/followers',
   'following_url': 'https://api.github.com/users/Simon99/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Simon99/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Simon99/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Simon99/subscriptions',
   'organizations_url': 'https://api.github.com/users/Simon99/orgs',
   'repos_url': 'https://api.github.com/users/Simon99/repos',
   'events_url': 'https://api.github.com/users/Simon99/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Simon99/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2026-03-05T12:21:38Z',
  'updated_at': '2026-03-05T13:02:17Z',
  'closed_at': None,
  'assignee': None,
  'author_association': 'NONE',
  'type': None,
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/64408',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/64408',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/64408.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/64408.patch',
   'merged_at': None},
  'body': "Fixes #64280\n\n## Summary\nFix pd.array to properly reject multidimensional numpy arrays as documented.\n\n## Background\nThe pd.array documentation states that it should raise ValueError when data is not 1-dimensional. However, it was accepting multidimensional numpy arrays when dtype was explicitly specified:\n\n```python\npd.array([[1, 9], [2, 6], [3, 5]], dtype=np.float64)\n# Incorrectly accepted, created a 2D NumpyExtensionArray\n```\n\n## Changes\n- Added dimensionality check after `extract_array()` in `pandas.core.construction.array()`\n- Raises `ValueError` with clear message for multidimensional inputs\n- Added regression tests for 2D and 3D array inputs\n\n## Testing\n```python\n# Now correctly raises ValueError\npd.array([[1, 9], [2, 6]], dtype=np.float64)\n# ValueError: Cannot pass 2-dimensional array to 'pandas.array'. Expected 1-dimensional data.\n```\n\nTests added in `pandas/tests/arrays/test_array.py`:\n- `test_pd_array_rejects_multidimensional_numpy_array`\n\n",
  'closed_by': None,