In [66]:
import numpy as np
import pandas as pd

In [67]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
# concatinating a string
"https://" + "github.com" + "/jkmloom"

'https://github.com/jkmloom'

In [7]:
# concatinating two dataframes
df1 = df[["Name", "Sex", "Age"]][0:5]
df2 = df[["Name", "Sex", "Age"]][5:10]

In [13]:
print(f"df1:\n****\n{df1}\n{"***"*22}\ndf2:\n****\n{df2}")

df1:
****
                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
******************************************************************
df2:
****
                                                Name     Sex   Age
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [16]:
# concatenating two dataframes with indexes that are not equal (same)
pd.concat([df1, df2])
# default >> axis = 0
# concatenate row wise

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [15]:
pd.concat([df1, df2], axis = 1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN
2,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",male,NaN
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",male,54.0
7,NaN,NaN,NaN,"Palsson, Master. Gosta Leonard",male,2.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [19]:
# for same index values cocatenation is simple (generally results in no null values)
df2.reset_index(drop = True, inplace = True)
df2

                                                Name     Sex   Age
0                                   Moran, Mr. James    male   NaN
1                            McCarthy, Mr. Timothy J    male  54.0
2                     Palsson, Master. Gosta Leonard    male   2.0
3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
4                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [29]:
print(f"df1:\n****\n{df1}\n{"***"*22}\ndf2:\n****\n{df2}")

df1:
****
                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
******************************************************************
df2:
****
                                                Name     Sex   Age
0                                   Moran, Mr. James    male   NaN
1                            McCarthy, Mr. Timothy J    male  54.0
2                     Palsson, Master. Gosta Leonard    male   2.0
3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
4                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [31]:
# concatenating df1 and df2 with same indexes
pd.concat([df1, df2], axis = 1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,"Moran, Mr. James",male,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,"McCarthy, Mr. Timothy J",male,54.0
2,"Heikkinen, Miss. Laina",female,26.0,"Palsson, Master. Gosta Leonard",male,2.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
4,"Allen, Mr. William Henry",male,35.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [32]:
# concatenation >> keeping dataframes horizontally or verticially

In [33]:
# merging dataframes
# inner merge >> merge based on common elements
# right merge >> merge based on elements from the right
# left merge >> merge based on elements from the left
# outter merge >> all elements of both the dataframes
# cross merge >> every permutation & combination of elements are there

In [43]:
df1 = pd.DataFrame({
    'key 1' : [1, 2, 4, 5, 6],
    'key 2' : [4, 5, 6, 7, 8],
    'key 3' : [3, 4, 5, 6, 6]
})
df1

   key 1  key 2  key 3
0      1      4      3
1      2      5      4
2      4      6      5
3      5      7      6
4      6      8      6

In [44]:
df2 = pd.DataFrame({
    'key 1' : [1, 2, 45, 6, 67],
    'key 4' : [56, 5, 6, 7, 8],
    'key 5' : [3, 56, 5, 6, 6]
})
df2

   key 1  key 4  key 5
0      1     56      3
1      2      5     56
2     45      6      5
3      6      7      6
4     67      8      6

In [45]:
# merging df1 and df2
# inner merge
pd.merge(df1, df2, how = "inner")

   key 1  key 2  key 3  key 4  key 5
0      1      4      3     56      3
1      2      5      4      5     56
2      6      8      6      7      6

In [47]:
# left >> all elements from the left dataframe
pd.merge(df1, df2, how = "left")

   key 1  key 2  key 3  key 4  key 5
0      1      4      3   56.0    3.0
1      2      5      4    5.0   56.0
2      4      6      5    NaN    NaN
3      5      7      6    NaN    NaN
4      6      8      6    7.0    6.0

In [48]:
# right >> all elements from the right dataframe
pd.merge(df1, df2, how = "right")

   key 1  key 2  key 3  key 4  key 5
0      1    4.0    3.0     56      3
1      2    5.0    4.0      5     56
2     45    NaN    NaN      6      5
3      6    8.0    6.0      7      6
4     67    NaN    NaN      8      6

In [53]:
# outer >> all the common elements of the common column
print(f"df1:\n{df1}\n{"***"*20}\ndf2:\n{df2}\n{"***"*20}")

print("Outer merge: df1, df2")
pd.merge(df1, df2, how = 'outer')

df1:
   key 1  key 2  key 3
0      1      4      3
1      2      5      4
2      4      6      5
3      5      7      6
4      6      8      6
************************************************************
df2:
   key 1  key 4  key 5
0      1     56      3
1      2      5     56
2     45      6      5
3      6      7      6
4     67      8      6
************************************************************
Outer merge: df1, df2

   key 1  key 2  key 3  key 4  key 5
0      1    4.0    3.0   56.0    3.0
1      2    5.0    4.0    5.0   56.0
2      4    6.0    5.0    NaN    NaN
3      5    7.0    6.0    NaN    NaN
4      6    8.0    6.0    7.0    6.0
5     45    NaN    NaN    6.0    5.0
6     67    NaN    NaN    8.0    6.0

In [55]:
# cross join >> permutation of dataframes
pd.merge(df1, df2, how = "cross")

    key 1_x  key 2  key 3  key 1_y  key 4  key 5
0         1      4      3        1     56      3
1         1      4      3        2      5     56
2         1      4      3       45      6      5
3         1      4      3        6      7      6
4         1      4      3       67      8      6
5         2      5      4        1     56      3
6         2      5      4        2      5     56
7         2      5      4       45      6      5
8         2      5      4        6      7      6
9         2      5      4       67      8      6
10        4      6      5        1     56      3
11        4      6      5        2      5     56
12        4      6      5       45      6      5
13        4      6      5        6      7      6
14        4      6      5       67      8      6
15        5      7      6        1     56      3
16        5      7      6        2      5     56
17        5      7      6       45      6      5
18        5      7      6        6      7      6
19        5      7      6       67      8      6
20        6      8      6        1     56      3
21        6      8      6        2      5     56
22        6      8      6       45      6      5
23        6      8      6        6      7      6
24        6      8      6       67      8      6

In [57]:
# using specific columns to merge dataframes
pd.merge(df1, df2, how = 'left', left_on = "key 2", right_on = "key 4")

   key 1_x  key 2  key 3  key 1_y  key 4  key 5
0        1      4      3      NaN    NaN    NaN
1        2      5      4      2.0    5.0   56.0
2        4      6      5     45.0    6.0    5.0
3        5      7      6      6.0    7.0    6.0
4        6      8      6     67.0    8.0    6.0

In [68]:
# join >> join works based on index
# merge >> merge works based on columns
df1 = pd.DataFrame({
    'key 1' : [1, 2, 4, 5, 6],
    'key 2' : [4, 5, 6, 7, 8],
    'key 3' : [3, 4, 5, 6, 6]
}, index = ['a', 'b', 'c', 'd', 'e'])
df1

   key 1  key 2  key 3
a      1      4      3
b      2      5      4
c      4      6      5
d      5      7      6
e      6      8      6

In [71]:
df2 = pd.DataFrame({
    'key 6' : [1, 2, 45, 6, 67],
    'key 4' : [56, 5, 6, 7, 8],
    'key 5' : [3, 56, 5, 6, 6]
}, index = ['a', 'b', 'h', 'i', 'j'])
df2

   key 6  key 4  key 5
a      1     56      3
b      2      5     56
h     45      6      5
i      6      7      6
j     67      8      6

In [73]:
# joining columns of dataframes based on common indexes
df1.join(df2, how = 'inner')

   key 1  key 2  key 3  key 6  key 4  key 5
a      1      4      3      1     56      3
b      2      5      4      2      5     56

In [74]:
# joining left
df1.join(df2, how = 'left')

   key 1  key 2  key 3  key 6  key 4  key 5
a      1      4      3    1.0   56.0    3.0
b      2      5      4    2.0    5.0   56.0
c      4      6      5    NaN    NaN    NaN
d      5      7      6    NaN    NaN    NaN
e      6      8      6    NaN    NaN    NaN

In [75]:
# joining right
df1.join(df2, how = 'right')

   key 1  key 2  key 3  key 6  key 4  key 5
a    1.0    4.0    3.0      1     56      3
b    2.0    5.0    4.0      2      5     56
h    NaN    NaN    NaN     45      6      5
i    NaN    NaN    NaN      6      7      6
j    NaN    NaN    NaN     67      8      6

In [76]:
df1.join(df2, how = 'outer')

   key 1  key 2  key 3  key 6  key 4  key 5
a    1.0    4.0    3.0    1.0   56.0    3.0
b    2.0    5.0    4.0    2.0    5.0   56.0
c    4.0    6.0    5.0    NaN    NaN    NaN
d    5.0    7.0    6.0    NaN    NaN    NaN
e    6.0    8.0    6.0    NaN    NaN    NaN
h    NaN    NaN    NaN   45.0    6.0    5.0
i    NaN    NaN    NaN    6.0    7.0    6.0
j    NaN    NaN    NaN   67.0    8.0    6.0

In [77]:
df1.join(df2, how='cross')

    key 1  key 2  key 3  key 6  key 4  key 5
0       1      4      3      1     56      3
1       1      4      3      2      5     56
2       1      4      3     45      6      5
3       1      4      3      6      7      6
4       1      4      3     67      8      6
5       2      5      4      1     56      3
6       2      5      4      2      5     56
7       2      5      4     45      6      5
8       2      5      4      6      7      6
9       2      5      4     67      8      6
10      4      6      5      1     56      3
11      4      6      5      2      5     56
12      4      6      5     45      6      5
13      4      6      5      6      7      6
14      4      6      5     67      8      6
15      5      7      6      1     56      3
16      5      7      6      2      5     56
17      5      7      6     45      6      5
18      5      7      6      6      7      6
19      5      7      6     67      8      6
20      6      8      6      1     56      3
21      6      8      6      2      5     56
22      6      8      6     45      6      5
23      6      8      6      6      7      6
24      6      8      6     67      8      6

In [78]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [82]:
# converting fare from euro to inr
# assuming euro 1 = inr 90
# obj.apply() >> to apply a function on all the elements/values of a column
df['Fare_inr'] = df['Fare'].apply(lambda x: x*90)

In [81]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500

In [83]:
df["Fare_inr"]

0       652.500
1      6415.497
2       713.250
3      4779.000
4       724.500
         ...
886    1170.000
887    2700.000
888    2110.500
889    2700.000
890     697.500
Name: Fare_inr, Length: 891, dtype: float64

In [84]:
# creating a column for storing length of the name
df["Name_len"] = df['Name'].apply(lambda x: len(x))

In [85]:
df['Name_len']

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name_len, Length: 891, dtype: int64

In [86]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19

In [87]:
# applying user defined function
def conversion(x):
    return x*90

In [89]:
# applying the above defined funtion to "Fare" column from original dataframe
df["Fare1"] = df["Fare"].apply(conversion)

In [90]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len,Fare1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,652.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,6415.497
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,713.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4779.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,724.500

In [91]:
# create a column which shows the status of fare: cheap, medium, high
def create_flag(x):
    if x < 10:
        return "cheap"
    if x >= 10 and x < 20:
        return "medium"
    else:
        return "high"

In [95]:
df["Fare_flag"] = df["Fare"].apply(create_flag)

In [96]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_inr,Name_len,Fare1,Fare_flag
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,652.500,23,652.500,cheap
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,6415.497,51,6415.497,high
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,713.250,22,713.250,cheap
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4779.000,44,4779.000,high
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,724.500,24,724.500,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1170.000,21,1170.000,medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2700.000,28,2700.000,high
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2110.500,40,2110.500,high
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2700.000,21,2700.000,high
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,697.500,19,697.500,cheap

In [103]:
data = {
    'a': [1, 2, 3, 4],
    'b': [5, 5, 6, 7],
    'c': ['jkmloom', 'jkmcode', 'jkmjatin', 'internet']
}
df1 = pd.DataFrame(data)

In [104]:
df1

   a  b         c
0  1  5   jkmloom
1  2  5   jkmcode
2  3  6  jkmjatin
3  4  7  internet

In [105]:
df1.set_index('c', inplace = True)
df1

          a  b
c
jkmloom   1  5
jkmcode   2  5
jkmjatin  3  6
internet  4  7

In [107]:
df1.reset_index(drop=True, inplace=True)
df1

   a  b
0  1  5
1  2  5
2  3  6
3  4  7

In [109]:
# making new index for series and dataframe
df1.reindex([1, 2, 3, 0])

   a  b
1  2  5
2  3  6
3  4  7
0  1  5

In [110]:
# iterating the above dataframe in a for loop
for i in df1.iterrows(): # iterates row-wise
    print(i, ".....")

(0, a    1
b    5
Name: 0, dtype: int64) .....
(1, a    2
b    5
Name: 1, dtype: int64) .....
(2, a    3
b    6
Name: 2, dtype: int64) .....
(3, a    4
b    7
Name: 3, dtype: int64) .....

In [117]:
print(f"{df1}\n{"***"*9}")
for i in df1.items(): # inerates column-wise
    print(i, "....")

   a  b
0  1  5
1  2  5
2  3  6
3  4  7
***************************
('a', 0    1
1    2
2    3
3    4
Name: a, dtype: int64) ....
('b', 0    5
1    5
2    6
3    7
Name: b, dtype: int64) ....

In [118]:
# applying a function to the entire dataframe
def func_sum(x):
    return x.sum()

In [121]:
df1.apply(func_sum, axis = 0) # axis = 0 (default) : same happens when left unspecifies

a    10
b    23
dtype: int64

In [122]:
df1.apply(func_sum, axis = 1)

0     6
1     7
2     9
3    11
dtype: int64

In [123]:
# can also use obj.applymap() for applying a function
df1.applymap(lambda x: x**2)

C:\Users\ROG\AppData\Local\Temp\ipykernel_21540\2420529681.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x: x**2)

    a   b
0   1  25
1   4  25
2   9  36
3  16  49

In [124]:
# instead of obj.applymap() we should now rather use obj.map()
df1.map(lambda x: x**2)

    a   b
0   1  25
1   4  25
2   9  36
3  16  49

In [125]:
data = {
    'a': [100, 200, 13, 4],
    'b': [5, 5, 6, 7],
    'c': ["jkmloom", "jmkcode", "jkmjatin", "jkmvibe"]
}
df2 = pd.DataFrame(data)

In [126]:
df2

     a  b         c
0  100  5   jkmloom
1  200  5   jmkcode
2   13  6  jkmjatin
3    4  7   jkmvibe

In [127]:
# sorting values from a dataframe
df2.sort_values(by = "a")

     a  b         c
3    4  7   jkmvibe
2   13  6  jkmjatin
0  100  5   jkmloom
1  200  5   jmkcode